const PHOTO_POOL = [
  // Базовый набор фото
  "/photos/image.png",
  "/photos/image copy.png",
  "/photos/image copy 2.png",
  "/photos/image copy 3.png",
  "/photos/image copy 4.png",
  "/photos/image copy 5.png",
  "/photos/image copy 6.png",
  "/photos/image copy 7.png",
  "/photos/image copy 8.png",
  "/photos/image copy 9.png",
  "/photos/image copy 10.png",
  "/photos/image copy 11.png",
  // Дополнительные фото из папки «фотки 2»
  "/photos2/image.png",
  "/photos2/image copy.png",
  "/photos2/image copy 2.png",
  "/photos2/image copy 3.png",
  "/photos2/image copy 4.png",
  "/photos2/image copy 5.png",
  "/photos2/image copy 6.png",
  "/photos2/image copy 7.png",
  "/photos2/image copy 8.png",
];

function pickPhotos(startIdx, count = 6) {
  const out = [];
  for (let i = 0; i < count; i++) out.push(PHOTO_POOL[(startIdx + i) % PHOTO_POOL.length]);
  return out;
}

export const properties = [
  {
    id: "S-1001",
    slug: "apartment-sea-view-torrevieja",
    listingType: "sale",
    title: "Апартаменты с видом на море",
    city: "Торревьеха",
    bedrooms: 2,
    areaM2: 68,
    priceEur: 165000,
    badges: ["у моря", "после ремонта"],
    images: pickPhotos(0, 7),
    views: 1240,
    rating: 4.8,
    description:
      "Светлые апартаменты в шаговой доступности от пляжа. Удобная планировка, терраса, развитая инфраструктура района.",
  },
  {
    id: "S-1002",
    slug: "villa-marabella-private-pool",
    listingType: "sale",
    title: "Вилла с приватным бассейном",
    city: "Марбелья",
    bedrooms: 4,
    areaM2: 210,
    priceEur: 1250000,
    badges: ["бассейн", "терраса"],
    images: pickPhotos(2, 8),
    views: 892,
    rating: 5.0,
    description:
      "Современная вилла в тихом районе. Просторная гостиная, 4 спальни, зона отдыха на участке и парковка.",
  },
  {
    id: "S-1003",
    slug: "new-build-valencia-city",
    listingType: "sale",
    title: "Новостройка в городе",
    city: "Валенсия",
    bedrooms: 3,
    areaM2: 92,
    priceEur: 315000,
    badges: ["новостройка", "инфраструктура"],
    images: pickPhotos(4, 7),
    views: 1560,
    rating: 4.5,
    description:
      "Квартира в новом доме рядом с транспортом и сервисами. Подходит для жизни и долгосрочной аренды.",
  },
  {
    id: "S-1004",
    slug: "bungalow-finestrat-terrace",
    listingType: "sale",
    title: "Бунгало с террасой",
    city: "Финестрат",
    bedrooms: 2,
    areaM2: 74,
    priceEur: 249900,
    badges: ["терраса", "комплекс"],
    images: pickPhotos(6, 7),
    views: 734,
    rating: 4.2,
    description:
      "Бунгало в жилом комплексе с зоной отдыха. Хороший вариант для отдыха и инвестиций.",
  },
  {
    id: "S-1005",
    slug: "apartment-madrid-center",
    listingType: "sale",
    title: "Квартира в центре города",
    city: "Мадрид",
    bedrooms: 1,
    areaM2: 48,
    priceEur: 290000,
    badges: ["центр", "инвестиция"],
    images: pickPhotos(8, 6),
    views: 2100,
    rating: 4.8,
    description:
      "Компактная квартира в центре. Удобно для проживания или сдачи в аренду.",
  },

  {
    id: "S-1006",
    slug: "townhouse-costa-blanca-family",
    listingType: "sale",
    title: "Таунхаус на Коста-Бланка",
    city: "Коста-Бланка",
    bedrooms: 3,
    areaM2: 112,
    priceEur: 329000,
    badges: ["для семьи", "закрытый комплекс"],
    images: pickPhotos(10, 7),
    views: 1340,
    rating: 4.6,
    description:
      "Уютный таунхаус в семейном комплексе с бассейном и зелёными зонами. Удобный доступ к пляжу и инфраструктуре.",
  },
  {
    id: "S-1007",
    slug: "penthouse-barcelona-terrace",
    listingType: "sale",
    title: "Пентхаус с террасой в Барселоне",
    city: "Барселона",
    bedrooms: 2,
    areaM2: 96,
    priceEur: 690000,
    badges: ["терраса", "вид на город"],
    images: pickPhotos(10, 7),
    views: 1780,
    rating: 4.9,
    description:
      "Стильный пентхаус с большой террасой и панорамными видами. Идеален для жизни в динамичном городе у моря.",
  },
  {
    id: "S-1008",
    slug: "villa-alicante-modern",
    listingType: "sale",
    title: "Современная вилла в Аликанте",
    city: "Аликанте",
    bedrooms: 4,
    areaM2: 185,
    priceEur: 890000,
    badges: ["бассейн", "современный дизайн"],
    images: pickPhotos(8, 7),
    views: 980,
    rating: 4.7,
    description:
      "Современная вилла с панорамным остеклением, частным бассейном и зоной барбекю. Спокойный район недалеко от моря.",
  },
  {
    id: "S-1009",
    slug: "apartment-malaga-old-town",
    listingType: "sale",
    title: "Апартаменты в старом городе Малаги",
    city: "Малага",
    bedrooms: 2,
    areaM2: 74,
    priceEur: 245000,
    badges: ["исторический центр", "инвестиция"],
    images: pickPhotos(7, 6),
    views: 1640,
    rating: 4.4,
    description:
      "Атмосферные апартаменты в историческом центре, рядом с кафе, магазинами и набережной. Хороший вариант под аренду.",
  },
  {
    id: "S-1010",
    slug: "loft-valencia-river-park",
    listingType: "sale",
    title: "Лофт рядом с парком реки Турия",
    city: "Валенсия",
    bedrooms: 1,
    areaM2: 56,
    priceEur: 215000,
    badges: ["лофт", "рядом с парком"],
    images: pickPhotos(9, 6),
    views: 1210,
    rating: 4.3,
    description:
      "Светлый лофт с высоким потолком и большими окнами. В нескольких минутах от парка и центра города.",
  },
  {
    id: "S-1011",
    slug: "bungalow-benidorm-sea",
    listingType: "sale",
    title: "Бунгало недалеко от моря в Бенидорме",
    city: "Бенидорм",
    bedrooms: 2,
    areaM2: 82,
    priceEur: 275000,
    badges: ["у моря", "комплекс"],
    images: pickPhotos(5, 7),
    views: 1375,
    rating: 4.5,
    description:
      "Бунгало в комплексе с несколькими бассейнами и общей зоной отдыха. Пешая доступность до пляжа.",
  },
  {
    id: "S-1012",
    slug: "house-seville-patio",
    listingType: "sale",
    title: "Дом с внутренним патио в Севилье",
    city: "Севилья",
    bedrooms: 3,
    areaM2: 132,
    priceEur: 355000,
    badges: ["патио", "исторический район"],
    images: pickPhotos(3, 7),
    views: 910,
    rating: 4.6,
    description:
      "Традиционный андалусский дом с внутренним патио и несколькими террасами. Тихая улица, но рядом с центром.",
  },

  {
    id: "R-2001",
    slug: "rent-apartment-alicante-long-term",
    listingType: "rent",
    title: "Апартаменты для длительной аренды",
    city: "Аликанте",
    bedrooms: 2,
    areaM2: 65,
    rentEurPerMonth: 950,
    badges: ["длительная аренда"],
    images: pickPhotos(1, 7),
    views: 680,
    rating: 4.5,
    description:
      "Уютные апартаменты рядом с транспортом и магазинами. Для долгосрочного проживания.",
  },
  {
    id: "R-2002",
    slug: "rent-torrevieja-1br-near-beach",
    listingType: "rent",
    title: "1 спальня у моря",
    city: "Торревьеха",
    bedrooms: 1,
    areaM2: 44,
    rentEurPerMonth: 700,
    badges: ["у моря"],
    images: pickPhotos(3, 6),
    views: 1120,
    rating: 5.0,
    description:
      "Небольшая квартира в пешей доступности от пляжа. Отлично подходит для спокойной жизни.",
  },
  {
    id: "R-2003",
    slug: "rent-benidorm-3br-family",
    listingType: "rent",
    title: "Семейные апартаменты",
    city: "Бенидорм",
    bedrooms: 3,
    areaM2: 88,
    rentEurPerMonth: 1400,
    badges: ["для семьи", "инфраструктура"],
    images: pickPhotos(5, 7),
    views: 945,
    rating: 4.2,
    description:
      "Просторная квартира с 3 спальнями. Рядом школы, парки и удобные транспортные развязки.",
  },
  {
    id: "R-2004",
    slug: "rent-estepona-2br-terrace",
    listingType: "rent",
    title: "2 спальни с террасой",
    city: "Эстепона",
    bedrooms: 2,
    areaM2: 76,
    rentEurPerMonth: 1200,
    badges: ["терраса"],
    images: pickPhotos(7, 7),
    views: 520,
    rating: 4.8,
    description:
      "Комфортные апартаменты с террасой. Хорошее естественное освещение, ухоженный комплекс.",
  },
  {
    id: "R-2005",
    slug: "rent-barcelona-studio",
    listingType: "rent",
    title: "Студия в Барселоне",
    city: "Барселона",
    bedrooms: 0,
    areaM2: 32,
    rentEurPerMonth: 1100,
    badges: ["центр"],
    images: pickPhotos(9, 6),
    views: 1890,
    rating: 4.5,
    description:
      "Студия в городской локации: удобно для работы и поездок. Метро и сервисы рядом.",
  },

  {
    id: "R-2006",
    slug: "rent-valencia-river-park-2br",
    listingType: "rent",
    title: "2 спальни у парка реки Турия",
    city: "Валенсия",
    bedrooms: 2,
    areaM2: 70,
    rentEurPerMonth: 1150,
    badges: ["рядом с парком"],
    images: pickPhotos(11, 7),
    views: 760,
    rating: 4.4,
    description:
      "Уютные апартаменты рядом с зелёной зоной парка. Удобно для прогулок, спорта и жизни в городе.",
  },
  {
    id: "R-2007",
    slug: "rent-malaga-old-town-1br",
    listingType: "rent",
    title: "1 спальня в старом городе Малаги",
    city: "Малага",
    bedrooms: 1,
    areaM2: 52,
    rentEurPerMonth: 980,
    badges: ["исторический центр"],
    images: pickPhotos(0, 6),
    views: 540,
    rating: 4.3,
    description:
      "Аккуратные апартаменты в пешей доступности от набережной и старого города. Рядом кафе и магазины.",
  },
  {
    id: "R-2008",
    slug: "rent-alicante-sea-view-3br",
    listingType: "rent",
    title: "3 спальни с видом на море в Аликанте",
    city: "Аликанте",
    bedrooms: 3,
    areaM2: 96,
    rentEurPerMonth: 1650,
    badges: ["у моря", "для семьи"],
    images: pickPhotos(2, 7),
    views: 1320,
    rating: 4.7,
    description:
      "Семейные апартаменты с видом на море и просторной гостиной. Рядом пляж и прогулочная набережная.",
  },
  {
    id: "R-2009",
    slug: "rent-benidorm-cozy-studio",
    listingType: "rent",
    title: "Уютная студия в Бенидорме",
    city: "Бенидорм",
    bedrooms: 0,
    areaM2: 30,
    rentEurPerMonth: 750,
    badges: ["для отдыха"],
    images: pickPhotos(4, 6),
    views: 680,
    rating: 4.2,
    description:
      "Компактная студия в пешей доступности от моря и развлечений. Хороший вариант для отдыха парой.",
  },
  {
    id: "R-2010",
    slug: "rent-estepona-garden-2br",
    listingType: "rent",
    title: "Апартаменты с садиком в Эстепоне",
    city: "Эстепона",
    bedrooms: 2,
    areaM2: 78,
    rentEurPerMonth: 1300,
    badges: ["садик", "комплекс"],
    images: pickPhotos(6, 7),
    views: 590,
    rating: 4.6,
    description:
      "Квартира на первом этаже с небольшим частным садом. Закрытый комплекс с бассейном.",
  },
  {
    id: "R-2011",
    slug: "rent-barcelona-2br-eixample",
    listingType: "rent",
    title: "2 спальни в районе Эшампле",
    city: "Барселона",
    bedrooms: 2,
    areaM2: 68,
    rentEurPerMonth: 1500,
    badges: ["центр", "балкон"],
    images: pickPhotos(11, 7),
    views: 1490,
    rating: 4.5,
    description:
      "Квартира с балконом в престижном районе Эшампле. Удобно для жизни и работы в Барселоне.",
  },
  {
    id: "R-2012",
    slug: "rent-seville-patio-1br",
    listingType: "rent",
    title: "Апартаменты с патио в Севилье",
    city: "Севилья",
    bedrooms: 1,
    areaM2: 54,
    rentEurPerMonth: 900,
    badges: ["патио", "атмосфера"],
    images: pickPhotos(1, 6),
    views: 430,
    rating: 4.4,
    description:
      "Тёплые апартаменты с небольшим патио во внутреннем дворе. Тихий переулок, но рядом центр города.",
  },
];

export function getPropertyBySlug(slug) {
  return properties.find((p) => p.slug === slug) || null;
}

export function getPropertiesByType(listingType) {
  return properties.filter((p) => p.listingType === listingType);
}

